import {chromium} from '/tmp/npmtest/node_modules/playwright/index.mjs';
import {serve} from './server.mjs'; import fs from 'fs';
const PORT=8200+Math.floor(Math.random()*700); const s=await serve(PORT);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const pg=await b.newPage({viewport:{width:1280,height:800}});
const errs=[]; pg.on('pageerror',e=>errs.push('PE '+e.message)); pg.on('console',m=>{if(m.type()==='error')errs.push('CE '+m.text())});
await pg.addInitScript(()=>{Map.prototype.getOrInsertComputed??=function(k,f){if(!this.has(k))this.set(k,f(k));return this.get(k)}});
await pg.goto(`http://localhost:${PORT}/index.html`); await pg.waitForTimeout(1500);
await pg.screenshot({path:'dev/out/e2e-home.png'});
const bytes=[...fs.readFileSync('dev/samples/sample-ko.pdf')];
const r=await pg.evaluate(async b=>{const {host}=await import('./js/host.js');host._fake.put('C:\\Docs\\sample-ko.pdf',new Uint8Array(b));try{await app.openPdf('C:\\Docs\\sample-ko.pdf');return 'ok'}catch(e){return 'ERR '+e.stack}},bytes);
console.log(r); await pg.waitForTimeout(2000);
await pg.screenshot({path:'dev/out/e2e-open.png'});
console.log(await pg.evaluate(()=>({page:app.currentPage,title:app.documentTitle})));
const v3=await pg.evaluate(()=>({title:document.title,header:app.titleView.textContent,zoom:getComputedStyle(app.zoomPill).display!=='none',zlabel:app.zoomLabel.textContent,fab:getComputedStyle(app.addPageButton).display!=='none',welcome:getComputedStyle(app.welcomeCard).display==='none'}));
console.log('v3 ui', JSON.stringify(v3), v3.title==='Everynote'&&v3.header==='sample-ko.pdf'&&v3.zoom&&v3.zlabel==='100%'&&v3.fab&&v3.welcome?'PASS':'FAIL');
await pg.click('[data-tag="zoom_in"]'); await pg.waitForTimeout(300);
console.log('zoom in via pill', await pg.evaluate(()=>app.zoomLabel.textContent), await pg.evaluate(()=>app.zoomLabel.textContent)==='125%'?'PASS':'FAIL');
await pg.keyboard.press('ArrowRight'); await pg.waitForTimeout(1200);
console.log('ArrowRight page', await pg.evaluate(()=>app.currentPage), await pg.evaluate(()=>app.currentPage)===1?'PASS':'FAIL');
await pg.screenshot({path:'dev/out/e2e-v3.png'});
console.log(errs.join('\n')); await b.close(); s.close();
