// Evaluated inside the running app (via the WebView2 DevTools port) by tools/smoke.ps1. Must be one async expression.
(async () => {
  const out = { checks: {}, info: {} };
  const ok = (name, cond, extra) => { out.checks[name] = !!cond; if (!cond) out.info[name] = String(extra === undefined ? '' : extra).slice(0, 300); };
  try {
    const { host } = await import('/js/host.js');
    ok('native', host.native);
    const info = await host.info();
    out.info.app = JSON.stringify({ v: info.version, lib: info.library, args: info.args });
    ok('info', info && info.platform === 'win' && info.library && info.data, JSON.stringify(info));
    ok('args', info.args.length === 1 && /sample-ko\.pdf$/i.test(info.args[0]), JSON.stringify(info.args));
    // ---- fs round trips
    const dir = info.temp + '\\smoke test';
    await host.mkdir(dir);
    await host.writeText(dir + '\\a b.txt', '한글 text ✓');
    ok('text', (await host.readText(dir + '\\a b.txt')) === '한글 text ✓');
    const big = new Uint8Array(3 * 1024 * 1024 + 17); for (let i = 0; i < big.length; i++) big[i] = (i * 31 + (i >> 8)) & 255;
    await host.writeBytes(dir + '\\big.bin', big);
    const back = await host.readBytes(dir + '\\big.bin');
    let same = back.length === big.length; for (let i = 0; same && i < big.length; i += 997) if (back[i] !== big[i]) same = false;
    ok('bytes', same, back.length);
    const st = await host.stat(dir + '\\big.bin'); ok('stat', st.exists && !st.isDir && st.size === big.length, JSON.stringify(st));
    await host.move(dir + '\\big.bin', dir + '\\sub\\big2.bin'); await host.copy(dir + '\\sub\\big2.bin', dir + '\\sub\\big3.bin');
    const ls = await host.list(dir + '\\sub'); ok('list', ls.length === 2 && ls.every(e => !e.isDir && e.size === big.length && e.mtime > 1e12), JSON.stringify(ls));
    await host.delete(dir); ok('delete', !(await host.exists(dir)));
    // ---- file server + Range
    const url = await host.call('fs.url', { path: (window.app && window.app.documentUri) || info.args[0] });
    const r = await fetch(url, { headers: { Range: 'bytes=0-9' } });
    ok('range', r.status === 206 && (await r.text()).startsWith('%PDF-'), r.status);
    const rfull = await fetch(url); const buf = new Uint8Array(await rfull.arrayBuffer());
    ok('fetch-file', rfull.status === 200 && buf.length > 1000, rfull.status + ' ' + buf.length);
    let denied = false; try { await host.call('fs.url', { path: 'C:\\Windows\\win.ini' }); } catch (e) { denied = true; }
    ok('allowlist', denied);
    let denied2 = false; try { await host.call('fs.delete', { path: 'C:\\Windows\\Temp\\..\\win.ini' }); } catch (e) { denied2 = true; }
    ok('allowlist-write', denied2);
    // ---- fonts through the allow-list (Windows fonts are readable)
    const f = await fetch(await host.call('fs.url', { path: 'C:\\Windows\\Fonts\\malgun.ttf' })); ok('fonts', f.ok && (await f.arrayBuffer()).byteLength > 100000, f.status);
    // ---- misc methods
    ok('keepAwake', (await host.call('power.keepAwake', { on: true })) === true && (await host.call('power.keepAwake', { on: false })) === true);
    ok('fullscreen', (await host.call('window.fullscreen', { on: true })) === true);
    await new Promise(r => setTimeout(r, 600));
    ok('fullscreen-off', (await host.call('window.fullscreen', { on: false })) === true);
    const eng = await host.call('office.engines'); out.info.engines = JSON.stringify(eng);
    ok('engines', eng && 'word' in eng && 'libreoffice' in eng);
    await host.call('app.log', { msg: 'smoke log line' });
    // ---- OCR on a generated image
    try {
      const c = document.createElement('canvas'); c.width = 900; c.height = 260;
      const g = c.getContext('2d'); g.fillStyle = '#fff'; g.fillRect(0, 0, 900, 260); g.fillStyle = '#000'; g.font = '64px Arial';
      g.fillText('Hello World', 40, 100); g.fillText('PDF Note 2026', 40, 200);
      const png = c.toDataURL('image/png').split(',')[1];
      const o = await host.call('ocr.recognize', { png, lang: 'auto' });
      const text = o.words.map(w => w.text).join(' ');
      out.info.ocr = text + ' | ' + o.width + 'x' + o.height + ' lines=' + (new Set(o.words.map(w => w.line)).size);
      ok('ocr', /hello/i.test(text) && o.words.every(w => w.w > 0 && w.h > 0), text);
    } catch (e) { out.info.ocr = 'unavailable: ' + (e.message || e); out.checks.ocr = 'skip'; }
    // ---- office conversion when an engine exists (docx generated by the workflow, path passed in)
    const docx = window.__SMOKE_DOCX__;
    if (docx) {
      try { const { convertOffice } = await import('/js/office.js'); const msgs = [];
        const res = await convertOffice(docx, 'docx', t => msgs.push(t));
        const head = await host.readBytes(res.pdf); out.info.office = msgs.join(' > ') + ' -> ' + res.pdf + ' ' + head.length;
        ok('office-docx', head.length > 500 && String.fromCharCode(...head.subarray(0, 5)) === '%PDF-');
        await host.delete(res.pdf);
      } catch (e) { ok('office-docx', false, e.message); }
    }
    // ---- HWP conversion (rhwptopdf in a worker) on the generated sample
    if (window.__SMOKE_HWPX__) {
      try {
        const { convertHwp } = await import('/js/office.js'); const msgs = []; const t0 = performance.now();
        const bytes = await host.readBytes(window.__SMOKE_HWPX__);
        const pdf = await convertHwp(bytes, t => msgs.push(t));
        out.info.hwp = msgs.join(' > ') + ' -> ' + pdf.length + ' bytes in ' + Math.round(performance.now() - t0) + ' ms';
        ok('hwp', pdf.length > 500 && String.fromCharCode(...pdf.subarray(0, 5)) === '%PDF-');
        try { const { PdfDoc } = await import('/js/pdfdoc.js'); const d = await PdfDoc.open(pdf); const tx = await d.pageText(0);
          out.info.hwpText = d.pageCount + ' page(s): ' + String(tx).replace(/\s+/g, ' ').slice(0, 80); } catch (e) { out.info.hwpText = 'pdfdoc: ' + (e.message || e); }
      } catch (e) { ok('hwp', false, e.message); }
    }
    out.info.title = document.title; out.info.text = (document.body.innerText || '').replace(/\s+/g, ' ').slice(0, 160);
    out.info.hasApp = String(!!window.app);
  } catch (e) { out.checks.exception = false; out.info.exception = String((e && e.stack) || e).slice(0, 600); }
  return JSON.stringify(out);
})()
